name: SGA CI

on:
  pull_request_target:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sga_db:
        image: postgres:12
        env:
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: laravel
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-interaction

    - name: Set up environment
      run: |
        cp .env.example .env
        php artisan key:generate --show | xargs echo "APP_KEY=" >> .env
        echo "DB_CONNECTION=pgsql" >> .env
        echo "DB_HOST=sga_db" >> .env
        echo "DB_PORT=5432" >> .env
        echo "DB_DATABASE=laravel" >> .env
        echo "DB_USERNAME=laravel" >> .env
        echo "DB_PASSWORD=secret" >> .env
        # Adicione outras configurações do .env conforme necessário

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Migrations
      run: php artisan migrate

    - name: Run Unit and Feature Tests
      run: vendor/bin/phpunit

    - name: Run Laravel Dusk Tests
      run: php artisan dusk
