name: SGA CI

on:
  pull_request_target:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sga_db:
        image: postgres:12
        env:
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: laravel
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      run: |
        echo "APP_KEY=$(php artisan key:generate --show)" >> $GITHUB_ENV
        cp .env.example .env
        sed -i "s/DB_HOST=sga_db/DB_HOST=localhost/" .env
        sed -i "s/DB_USERNAME=laravel/DB_USERNAME=$\{{ env.POSTGRES_USER }}" .env
        sed -i "s/DB_PASSWORD=secret/DB_PASSWORD=$\{{ env.POSTGRES_PASSWORD }}" .env
        sed -i "s/APP_KEY=/APP_KEY=$\{{ env.APP_KEY }}/" .env

    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-interaction

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Migrations
      run: php artisan migrate

    - name: Run Unit and Feature Tests
      run: vendor/bin/phpunit

    - name: Run Laravel Dusk Tests
      run: php artisan dusk
